AWSTemplateFormatVersion : '2010-09-09'
Transform:
  - AWS::Serverless-2016-10-31

Description: my template
Resources:
  GetCompany:
      Type: AWS::Serverless::Function
      Properties:
        FunctionName: getCompany
        Handler: bank.getCompany
        Runtime: python3.6
        CodeUri: package/
        Policies:
          - DynamoDBReadPolicy:
              TableName: !Ref BankTable
          - DynamoDBWritePolicy:
              TableName: !Ref BankTable
        Environment:
          Variables:
            BANK_TABLE: !Ref BankTable
        Events:
          GetCompany:
            Type: Api
            Properties:
              RestApiId: !Ref MyAPI
              Path: "/company/{companyId}"
              Method: PUT
              
  
  MyAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: bank-api
      StageName: prod
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: swagger.yaml
            
  BankTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: bank-table
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S