AWSTemplateFormatVersion : '2010-09-09'
Transform:
    - AWS::Serverless-2016-10-31
Description: Lambda Cloudformation
Resources: 
  #Get movies option 1
  GetClient:
    Type: AWS::Serverless::Function
    Properties:
        FunctionName: getClient
        Handler: client.getClient
        Runtime: python3.6
        CodeUri: package/
        #Role: !GetAtt MyLambdaRole.Arn
        Policies:
          - DynamoDBReadPolicy:
              TableName: !Ref ClientsTable
        Environment:
          Variables:
            CLIENTS_TABLE: !Ref ClientsTable
        Events:
            GetClients:
              Type: Api
              Properties:
                RestApiId: !Ref MyAPI
                Path: "/clients/{client_id}"
                Method: GET
  PutClient:
    Type: AWS::Serverless::Function
    Properties:
        FunctionName: putClient
        Handler: client.putClient
        Runtime: python3.6
        CodeUri: package/
        Policies:
          - DynamoDBWritePolicy:
              TableName: !Ref ClientsTable
        #Role: !GetAtt MyLambdaRole.Arn
        Environment:
          Variables:
            CLIENTS_TABLE: !Ref ClientsTable
        Events:
            GetClients:
              Type: Api
              Properties:
                RestApiId: !Ref MyAPI
                Path: "/clients/{client_id}"
                Method: PUT
                
  MyAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: client-api
      StageName: prod
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: swaggerSMM.yaml
                   
    
  ClientsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: clients-table
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
            
  BankTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BankTable:
        Fn::ImportValue: BankTable